### ISSUE TITLE
endless_firestore does not support cloud_firestore 3.x

### ISSUE THREAD

**Issue by clayharris** [danReynolds/endless#5]
Apologies if this is the wrong project, but this is the repo linked in https://pub.dev/packages/endless_firestore and I couldn't find a more applicable github.

I'm trying to use endless_firestore, but the `pub get` fails due to endless_firestore relying on an old version of cloud_firestore.

> Because {project} depends on endless_firestore ^1.3.0 which depends on cloud_firestore ^2.5.3, cloud_firestore ^2.5.3 is required.
So, because {project} depends on cloud_firestore ^3.1.6, version solving failed.

**Comment by danReynolds** [comment]
Gotcha, thanks for reaching out. I'll update it later today.

**Comment by danReynolds** [comment]
@clayharris updated and published under version 1.4.0

**Comment by clayharris** [comment]
Thanks so much for the quick response and update!
